apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: coreroller/postgres:1.0.4
        ports:
        - containerPort: 5432
