apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rollerd
spec:
  replicas: 1
  selector:
    app: rollerd
  template:
    metadata:
      labels:
        app: rollerd
    spec:
      containers:
      - name: rollerd
        image: coreroller/rollerd:1.0.4
        ports:
        - containerPort: 8000
        env:
        - name: COREROLLER_DB_URL
          value: postgres://postgres@postgresql:5432/coreroller?sslmode=disable
