apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rollerd
  namespace: default
spec:
  replicas: 50
  template:
    metadata:
      labels:
        app: rollerd
    spec:
      containers:
      - name: rollerd
        image: coreroller/rollerd:1.0.5
        command: ["coreroller/rollerd", "-http-static-dir=/coreroller/static", "-host-coreos-packages=true", "-coreos-packages-path=/store", "-coreroller-url=http://192.168.1.135:8000"]
        volumeMounts:
         - name: store
           mountPath: /store
        ports:
        - containerPort: 8000
        env:
        - name: COREROLLER_DB_URL
          value: postgres://postgres@postgresql:5432/coreroller?sslmode=disable

      volumes:
      - name: store
        emptyDir: {}
