apiVersion: v1
kind: Namespace
metadata:
  name: provisioners

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: provdeployments
  name: provisioner-deployments
  namespace: provisioners
spec:
  replicas: 1
  selector:
    matchLabels:
      run: provdeployments
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: provdeployments
    spec:
      containers:
      - env:
        - name: GIT_SYNC_REPO
          value: git@github.com:lukasz-bielinski/test-objects.git
        - name: GIT_SYNC_DEST
          value: /git
        - name: GIT_PULL_TYPE
          value: AUTO
        - name: GIT_SYNC_WAIT
          value: "6"
        image: lukaszbielinski/git-sync:0.7.2
        imagePullPolicy: Always
        name: git-sync
        # resources:
        #   limits:
        #     cpu: 50m
        #     memory: 150Mi
        #   requests:
        #     cpu: 10m
        #     memory: 10Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /git
          name: markdown
        - mountPath: /root/.ssh/klucze
          name: klucze
      - env:
        - name: PROVISONING_TYPE
          value: force          
        - name: DEPLOYMENT_DIR
        - name: PROV_TYPE
          value: generic
      #  image: lukaszbielinski/kubectl-image:0.30.3-alpine
        image: docker-snapshot.otlabs.fr/kubectl:latest
        imagePullPolicy: Always
        name: prov
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 150Mi
        #   requests:
        #     cpu: 50m
        #     memory: 50Mi
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /src
          name: markdown
      - name: prov-ns
        image: docker-snapshot.otlabs.fr/kubectl:latest
        env:
        - name: PROVISONING_TYPE
          value: force
        - name: PROV_TYPE
          value: quota
        - name: NS_DIR
          value: namespaces
        volumeMounts:
        - name: markdown
          mountPath: /src
      - name: prov-configmaps
        image: docker-snapshot.otlabs.fr/kubectl:latest
        env:
        - name: PROVISONING_TYPE
          value: force
        - name: PROV_TYPE
          value: configmap
        - name: CONFIGMAPS_DIR
          value: configmaps
        volumeMounts:
        - name: markdown
          mountPath: /src
      - name: prov-secrets
        image: docker-snapshot.otlabs.fr/kubectl:latest
        env:
        - name: PROVISONING_TYPE
          value: force
        - name: PROV_TYPE
          value: secrets
        - name: SECRETS_DIR
          value: secrets
        volumeMounts:
        - name: markdown
          mountPath: /src

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 2
      volumes:
      - emptyDir: {}
        name: markdown
      - name: klucze
        secret:
          defaultMode: 420
          secretName: klucze
