apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  namespace: infra
  name: vip-192-168-1-130
  labels:
    app-name: vip-192-168-1-130

spec:
  template:
    metadata:
      labels:
        name: vip-192-168-1-130

    spec:
      # nodeSelector:
      #   zone: frontend
      dnsPolicy: ClusterFirst
      hostNetwork: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30

      containers:
        - name: keepalived-vip
          image: lukaszbielinski/docker-ingress-controller-haproxy
          #image: lukaszbielinski/ing:02
          imagePullPolicy: Always
          securityContext:
            privileged: true
          # resources:
          #   requests:
          #     cpu: 30m
          #     memory: 32Mi
          #   limits:
          #     cpu: 1
          #     memory: 48Mi
          env:
            - name: VIP
              value: "192.168.1.130"
            - name: MASK
              value: "32"
            - name: VROUTERID
              value: "130"
            - name: STATE
              value: "MASTER"
            - name: INTERFACE
              value: "eth0"
            - name: PRIORITY
              value: "100"
            - name: ADVERT
              value: "5"
            - name: AUTHPASS
              value: sdovn12434sfwnwd
            - name: SERVICE
              value: kubernetes-dashboard
            - name: NAMESPACE
              value: kube-system
          volumeMounts:
          - mountPath: /sys
            name: sys
          - mountPath: /sbin/modprobe
            name: modprobe
          - mountPath: /lib/modules
            name: modules

      volumes:
      - name: sys
        hostPath:
            path: /sys
      - name: modprobe
        hostPath:
            path: /sbin/modprobe
      - name: modules
        hostPath:
            path: /lib/modules

##
