apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-1
  namespace: abc
spec:
  replicas: 1
  revisionHistoryLimit: 50
  strategy:
      rollingUpdate:
        maxUnavailable: 5
        maxSurge: 1
  template:
    metadata:
      labels:
        run: nginx-1
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: test
        image: nginx:1.13.5-alpine
        # resources:
        #   requests:
        #     memory: "1Mi"
        #     cpu: "1m"
        #   limits:
        #     memory: "100Mi"
        #     cpu: "2000m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        # volumeMounts:
        #  - name: www
        #    mountPath: /usr/share/nginx/html/u
        # - name: hooks
        #   mountPath: /hooks
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["echo","$MY_POD_IP",">","/usr/share/nginx/html/u","&&","/usr/sbin/nginx","-s","winch"]
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 35
          timeoutSeconds: 1

        readinessProbe:
          tcpSocket:
              port: 80
          initialDelaySeconds: 34
          timeoutSeconds: 1


      # volumes:
      # # - name: secr
      # #   emptyDir: {}
      # - name: www
      #   secret:
      #     secretName: www
      # # - name: mypd
      # #   persistentVolumeClaim:
      # #     claimName: nginx-1
      #

---


apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-1
  name: nginx-1
  namespace: default
spec:
  # externalIPs:
  # - 192.168.1.130
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 444
    protocol: TCP

  selector:
    run: nginx-1
#
