apiVersion: v1
kind: Service
metadata:
  labels:
    component: elasticsearch
    role: client
  name: elasticsearch
  namespace: logging
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
    role: client

  externalIPs:
    - "172.16.239.71"
    - "172.16.236.75"
#
#
