apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kafka-manager
  name: kafka-manager
  namespace: kafka-cluster
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    k8s-app: kafka-manager

  externalIPs:
    - "172.16.239.71"
