apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: iperf-client
  name: iperf-client
  namespace: network-performance
spec:
  replicas: 50
  selector:
    matchLabels:
      run: iperf-client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: iperf-client
    spec:
      containers:
      - image: lukaszbielinski/network-performance-docker
        command: ["iperf3", "-s"]
        imagePullPolicy: Always
        name: iperf-client
        ports:
        - containerPort: 5201
          protocol: TCP
        - containerPort: 12865
          protocol: TCP

      terminationGracePeriodSeconds: 1
