filebeat.registry_file: /var/log/containers/filebeat_registry

filebeat.prospectors:
-
  paths:
    - "/var/log/containers/*.log"
  symlinks: true
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^\s'
  multiline.match: after
  document_type: test-k8s

processors:
- decode_json_fields:
    when.regexp:
      message: '^{'
    fields: message
    target:
- drop_fields:
    when.regexp:
      message: '^{'
    fields: message


# output.logstash:
#     hosts: ${LOGSTASH_HOSTS:?No logstash host configured. Use env var LOGSTASH_HOSTS to set hosts.}
#     timeout: 15

logging.level: ${LOG_LEVEL:error}

output.kafka:
  enabled: true
  hosts: ["lb-kafka.kafka-cluster:9092"]
  topic: k8slogstsm
  max_retries: -1
  keep_alive: 5
  flush_interval: 5
  partition.round_robin:
    reachable_only: true
  required_acks: 1
