apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: logstash
  namespace: logging
spec:
  maxReplicas: 9
  minReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: logstash
  targetCPUUtilizationPercentage: 80
