apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: logstash
  name: logstash
  namespace: logging
spec:
  ports:
  - port: 5044
    protocol: TCP
    targetPort: 5044
  selector:
    k8s-app: logstash

  externalIPs:
    - "172.16.239.71"

     #
