kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pod-reader-binding
  namespace: infra
subjects:
- kind: ServiceAccount
  name: default
  namespace: infra
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
