apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster:v1.2.0
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes.summary_api:''
        - --sink=influxdb:http://monitoring-influxdb:8086
      - name: eventer
        image: gcr.io/google_containers/heapster:v1.2.0
        command:
        - /eventer
        - --source=kubernetes:''
        - --sink=influxdb:http://monitoring-influxdb:8086


##
