apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: logger
  namespace: simple-logger
  labels:
    k8s-app: logger
spec:
  replicas: 50
  revisionHistoryLimit: 2
  strategy:
      rollingUpdate:
        maxUnavailable: 1
  template:
    metadata:
      labels:
        k8s-app: logger
    spec:
      containers:
      - name: logger
        image: lukaszbielinski/simple-logger-app:0.0.2-SNAPSHOT
        imagePullPolicy: Always
