apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-1
  namespace: default
spec:
  replicas: 3
  strategy:
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  template:
    metadata:
      labels:
        run: nginx-1
    spec:
      containers:
      - name: test
        image: nginx:1.11-alpine
        # resources:
        #   requests:
        #     memory: "1Mi"
        #     cpu: "1m"
        #   limits:
        #     memory: "100Mi"
        #     cpu: "2000m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        # volumeMounts:
        # # - name: mypd
        # #   mountPath: /mypd
        # - name: hooks
        #   mountPath: /hooks
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["/usr/sbin/nginx","-s","quit"]

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5

        readinessProbe:
          tcpSocket:
              port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 5


      # volumes:
      # - name: secr
      #   emptyDir: {}
      # - name: hooks
      #   secret:
      #     secretName: hooks
      # - name: mypd
      #   persistentVolumeClaim:
      #     claimName: nginx-1

---


apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-1
  name: nginx-1
  namespace: default
spec:
  externalIPs:
  - 192.168.1.130
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx-1

#
