apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-1
  namespace: default
spec:
  replicas: 2
  strategy:
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
  template:
    metadata:
      labels:
        run: nginx-1
    spec:
      terminationGracePeriodSeconds: 100
      containers:
      - name: test
        image: nginx:1.13-alpine
        # resources:
        #   requests:
        #     memory: "1Mi"
        #     cpu: "1m"
        #   limits:
        #     memory: "100Mi"
        #     cpu: "2000m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
         - name: www
           mountPath: /usr/share/nginx/html/u
        # - name: hooks
        #   mountPath: /hooks
        lifecycle:
          preStop:
            exec:
              # SIGTERM triggers a quick exit; gracefully terminate instead
              command: ["/usr/sbin/nginx","-s","winch"]

        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 2

        readinessProbe:
          tcpSocket:
              port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 2


      volumes:
      # - name: secr
      #   emptyDir: {}
      - name: www
        secret:
          secretName: www
      # - name: mypd
      #   persistentVolumeClaim:
      #     claimName: nginx-1

---


apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx-1
  name: nginx-1
  namespace: default
spec:
  # externalIPs:
  # - 192.168.1.130
  ports:
  - name: http
    port: 80
    protocol: TCP
  # - name: https
  #   port: 444
  #   protocol: TCP

  selector:
    run: nginx-1

#
